
package com.mycompany.proyecto_integrador1.Sistema;

import com.mycompany.proyecto_integrador1.Sistema.CandidateForm;


public class ConfigPanel extends javax.swing.JPanel {

  
    public ConfigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearCandidatos = new javax.swing.JButton();
        btnRegistrarVotantes = new javax.swing.JButton();

        btnCrearCandidatos.setText("Registrar Candidatos");
        btnCrearCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCandidatosActionPerformed(evt);
            }
        });

        btnRegistrarVotantes.setText("Registrar Votantes");
        btnRegistrarVotantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVotantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCandidatos)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRegistrarVotantes)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnCrearCandidatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarVotantes)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCandidatosActionPerformed
        // Por ejemplo, abrir el formulario para crear candidatos
        CandidateForm candidateForm = new CandidateForm();
        candidateForm.setVisible(true);

    }//GEN-LAST:event_btnCrearCandidatosActionPerformed

    private void btnRegistrarVotantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVotantesActionPerformed
        // Aquí puedes implementar la lógica para registrar votantes,
        // por ejemplo, leyendo un archivo Excel o mostrando otro formulario.
        javax.swing.JOptionPane.showMessageDialog(this, "Funcionalidad para registrar votantes");

    }//GEN-LAST:event_btnRegistrarVotantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCandidatos;
    private javax.swing.JButton btnRegistrarVotantes;
    // End of variables declaration//GEN-END:variables
}
